bounswe/2021SpringGroup12

- practice-app/README.md
- practice-app/practice-app.py
- practice-app/requirements.txt
This request is about issue #122. After this pull, we will be ready to go.
> Veyis practice app initial

- practice-app/src/main/db/mapper.py
- practice-app/src/main/db/schemas.py
- practice-app/src/main/helpers/books_helper.py
- practice-app/src/main/practice-app.py
Route methods are now 5-6 lines, divided code into helper functions. Moved database connections to a different class. Structure is now up to date.
> Veyis practice app organized

- practice-app/frontend/package-lock.json
- practice-app/frontend/src/App.vue
- practice-app/frontend/src/convert/views/ConvertHome.vue
- practice-app/frontend/src/convert/views/ConvertPost.vue
- practice-app/frontend/src/router/index.js
- practice-app/main/db/mapper.py
- practice-app/main/db/schemas.py
- practice-app/main/helpers/currency_helper.py
- practice-app/unittests/test_currency.py
currency conversion api: unittests, frontend added. Solved some minor errors in frontend files. Added some mistakenly deleted parts for currency convert api.
> currency conversion api: unittests, frontend added. 

- practice-app/frontend/src/anime/components/AnimeDetails.vue
- practice-app/frontend/src/anime/views/Post.vue
- practice-app/frontend/src/anime/views/SearchResults.vue
- practice-app/main/db/mapper.py
- practice-app/main/db/schemas.py
- practice-app/main/helpers/anime_helper.py
- practice-app/sqlfiles/create_tables.sql
- practice-app/unittests/test_animes.py
Some fixes to the AnimeAPI regarding validation of animes posted by users.
Some fixes to the AnimeUI related to the refactoring of the backend.
Unittests for AnimeApi
> Burakcan june9

- practice-app/backend/main/helpers/issue_helper.py
- practice-app/backend/main/main.py
- practice-app/frontend/package-lock.json
- practice-app/frontend/src/issues/pages/IssuesHome.vue
- practice-app/frontend/src/issues/pages/PostIssue.vue
-Deleted unused variable from issue_helper.py
-return type changes in main.py
-Name change in PostIssue.vue
> -Added download issues button to IssuesHome.vue

- application/backend/build.gradle
- application/backend/src/main/java/cmpe451/group12/beabee/config/security/WebSecurityConfig.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/controller/LoginController.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/controller/UserController.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/dto/UserDTO.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/model/Users.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/repository/UserRepository.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/service/LoginService.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/service/UserService.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/util/EmailSender.java
- application/backend/src/main/resources/application.properties
Resolves #249.
/users/forgot/{email_or_username} endpoint sends an email to user. After clicking that link in the mail, their data is coming to /reset/{token} endpoint. Only then password is changed.
Also fixes #251
> feature:(dev/backend): implemented password-forgot-reset feature #249

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/EntitiController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
Fixed #273 
Now you can get generic entities from endpoint "/entities/entity/{entity_id}
> feature request #273 implemented

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/EntitiController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GoalService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GroupGoalService.java
@batuhanovski  requested this endpoint at #345 , and I delivered.
* It returns all of the entities of a goal including entities of subgoals' and entities of subgoals' of subgoals.
* `/v2/entities/goal/{goal_id} ` is the path.
> request:(dev/backend): implements #345

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/EntitiController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/dto/entities/RoutineGetDTO.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/entities/EntitiMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/entities/EntitiShortMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/entities/RoutinePostMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/model/entities/Routine.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/model/goals/Subgoal.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/ResourceService.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/EntitiServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/GoalServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/ResourceServiceTest.java
* Routines are repeatable entities, therefore they need multiple ratings for each period.
* Made rating and deadline fields list.
* Overall rating is calculated by averages of each period.
* Rating a routine extends it to next deadline.
* To complete all, refer to "PUT entity endpoint"
* Also written unittests of this logic.
> Implemented routine rate, multiple deadlines logic

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
* prev version: `        new_task.setEntitiType(EntitiType.ROUTINE);`
* new version: `        new_task.setEntitiType(EntitiType.REFLECTION);`
> fixed createReflection entityType typo

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/Repository/resources/ResourceRepository.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/ResourceService.java
* also added entities of a goal to get all entities of a goal endpoint
> fixed resource deletion foreign key bug 

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/Repository/resources/ResourceRepository.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/EntitiController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GoalService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/ResourceService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/SubgoalService.java
* Users may compelte their task and rate them at the same time with this new endpoint!
> complete task endpoint

- application/android/app/src/main/java/com/group12/beabee/InputValidator.java
- application/android/app/src/main/java/com/group12/beabee/views/LoginActivity.java
- application/android/app/src/main/java/com/group12/beabee/views/SignUpActivity.java
- application/android/app/src/test/java/com/group12/beabee/InputValidatorUnitTest.java
Created InputValidator to check 
- if input is in email format
- if input has minimum length
- if input is empty
> InputValidator and UnitTests

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/dto/entities/RoutineGetDTO.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/dto/entities/TaskGetDTO.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/entities/RoutineGetMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/entities/TaskGetMapper.java
- application/backend/src/main/resources/application.properties
* Database in the server has some old data which does not compatible with current system.
* They cause the server to crash.
* This commit will clear the database.
- I changed `spring.jpa.hibernate.ddl-auto=update` to `spring.jpa.hibernate.ddl-auto=create-drop`
> clearing database in the AWS

- application/frontend/src/components/UserCalendar.tsx
- Mistakenly compare days of week of the deadline
- Closes #408
> Fix calendar display issue

- application/frontend/src/pages/GoalsPage.tsx
- closes #422
- Layout updated by using ant design grid layout
- notification added from ant design UI library
- modal added from ant design library
> update layout and alignment of Goals page

- application/frontend/src/components/GoalForm.tsx
- application/frontend/src/pages/GoalPage.tsx
- application/frontend/src/pages/GoalsPage.tsx
- application/frontend/src/pages/LinkEntity.tsx
Deadline field is deleted from 
-GoalPage, Add Goal Page, Edit Goal Page
-Sub-Goal Page vice versa.
> Removing Deadline field

- application/backend/src/main/java/cmpe451/group12/beabee/common/dto/UserGetDTO.java
- application/backend/src/main/java/cmpe451/group12/beabee/common/mapper/UserMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/common/model/Users.java
- application/backend/src/main/java/cmpe451/group12/beabee/common/service/UserService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/UserController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/enums/ActivityType.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/ActivityStreamService.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/dto/UserCredentialsGetDTO.java
Added necessary endpoints to implement the function of following and unfollowing other users.
> User follow and unfollow feature

- application/android/app/src/main/AndroidManifest.xml
- application/android/app/src/main/java/com/group12/beabee/network/ServiceAPI.java
- application/android/app/src/main/java/com/group12/beabee/network/mocking/MockService.java
- application/android/app/src/main/java/com/group12/beabee/views/LoginActivityForgotPage.java
- application/android/app/src/main/java/com/group12/beabee/views/LoginActivityTokenPage.java
- application/android/app/src/main/java/com/group12/beabee/views/SignUpActivity.java
- application/android/app/src/main/res/layout/activity_login_reset_password.xml
- application/android/app/src/main/res/layout/activity_login_reset_password_2.xml
2 new pages are initalized one for the user to request "reset password" other is to paste the token sent to email and enter the new password. 
Neccessary connections are made
> reset password feature

- application/backend/src/main/java/cmpe451/group12/beabee/common/model/Users.java
Changed OneToMany relationships of follower and following to ManyToOne to remove the unique key constraint on the database, that inhibits users from following more than one user.
> Bugfix for #483. Users now can follow more than one user.

- application/frontend/src/App.tsx
- application/frontend/src/pages/Dashboard.tsx
> Implement Frontend Analytics Page

- application/backend/src/main/java/cmpe451/group12/beabee/common/model/Users.java
- application/backend/src/main/java/cmpe451/group12/beabee/common/service/UserService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/UserController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/enums/ActivityType.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/PrototypeService.java
- application/backend/src/main/java/cmpe451/group12/beabee/login/dto/UserCredentialsPostDTO.java
- application/backend/src/main/resources/application.properties
Implements #489 
* Old json body: `{
"email": "veyis@mail.tr",
"password": "very_strong_password",
"username": "veyist"
}`
* New json body: `{
"email": "veyis@mail.tr",
"password": "very_strong_password",
"username": "veyist",
"name": "veyis",
"surname":"turgut"
}`
> added name surname fields to signup endpoint

- application/frontend/src/components/PasswordForm.tsx
- Added notification
- Added new form for token submission
- Closes #293
> Implement reset password page

- application/backend/src/main/java/cmpe451/group12/beabee/config/security/WebSecurityConfig.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/GoalController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/ActivityStreamService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/EntitiService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GoalService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/PrototypeService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/SubgoalService.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/ActivityStreamTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/EntitiServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/GoalServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/PrototypeServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/ResourceServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/SubgoalServiceTest.java
* Since we added new dependencies to the system, previous tests broken. Fixed them.
* Added unittests of activity stream.
* Fixed security configs before final presentation.
> activity stream unittests

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/GoalController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/GroupGoalController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GoalService.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GroupGoalService.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/GoalServiceTest.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/GroupGoalServiceTest.java
Added new endpoints and methods to goals and group goals. User can get all subgoals of a group goal or goal with its id.
> Added necessary end points to get subgoals of goals and group goals

- application/frontend/src/components/PrivacyPolicy.tsx
- application/frontend/src/components/RegistrationForm.tsx
- application/frontend/src/components/TermsAndConditions.tsx
Added these forms in register page: 
- privacy policy 
- terms and conditions
They show up as modal.
closes #510
> Implementation of privacy policy and terms and conditions

- application/android/app/src/main/java/com/group12/beabee/models/requests/LoginRequest.java
- application/android/app/src/main/java/com/group12/beabee/models/requests/SignUpRequest.java
- application/android/app/src/main/java/com/group12/beabee/views/LoginActivity.java
- application/android/app/src/main/java/com/group12/beabee/views/SignUpActivity.java
- application/android/app/src/main/res/layout/activity_login.xml
- application/android/app/src/main/res/layout/activity_sign_up.xml
With the change in backend:[issue #489](https://github.com/bounswe/2021SpringGroup12/issues/489) sign in and login takes name and username as well, So the name and surname fields are added to sign-in and login pages and UI's are rearranged accordingly, Also the message is changed when user is not able to login due to "no such user" error and the message is directly taken from backend.
> Name and surname added to sign-log-in

- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/controller/GroupGoalController.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/dto/goals/GroupGoalGetDto.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/mapper/goals/GroupGoalPostMapper.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/model/goals/GroupGoal.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/model/goals/Tag.java
- application/backend/src/main/java/cmpe451/group12/beabee/goalspace/service/GroupGoalService.java
- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/GroupGoalServiceTest.java
- Transferred Tag endpoints and fields implemented by @veyisTurgut to group goals.
- Users can add and remove tags from group goals.
- They also see the tags they added to a group goal.
- This solves #512
> Implemented Tag functionality for group goals.

- application/frontend/src/App.tsx
- application/frontend/src/pages/ProfilePage.tsx
I have implemented a basic profile page for the users. Here is an example of the page:
> Profile Page is completed

- application/frontend/src/pages/GoalPage.tsx
I have implemented publish buttons for normal goals.
Here is the example page for unpublished goal:
Here is the example page for a published goal:
> Publish buttons are added for normal group.

- application/frontend/src/pages/EditGoal.tsx
I just removed deadline field from editgoal page and everything seems working fine.
> Deadline field is deleted from EditGoal.tsx.

- application/backend/src/test/java/cmpe451/group12/beabee/goalspace/service/EntitiServiceTest.java
- Fixed the issue with `EntitiService` instance initialization in the test class. Added new parameters, since constructor is changed.
- Changed the existing tests regarding entiti link functionality, they tested the entiti-entiti link type. Now they cover the entirety of the entiti link method.
- Added new tests to test the new entiti-subgoal links. They cover the whole subgoal branch of the `entitiLink` method.
- Added new tests for `entitiDeleteLink` method. These new tests cover the whole of the entitiDeleteLink method.
> Fixing existing tests and writing new tests for entiti-link logic.

- application/frontend/src/App.tsx
- application/frontend/src/components/NavBar.tsx
- application/frontend/src/pages/GoalPage.tsx
- application/frontend/src/pages/SearchPage.tsx
- Implemented search page
- Done Backend connection 
- Need to update data display
- closes #519
> Implement search page

- application/android/app/src/main/java/com/group12/beabee/TagDialogCallback.java
- application/android/app/src/main/java/com/group12/beabee/Utils.java
- application/android/app/src/main/java/com/group12/beabee/models/GroupGoalDetail.java
- application/android/app/src/main/java/com/group12/beabee/models/responses/GoalDetail.java
- application/android/app/src/main/java/com/group12/beabee/network/ServiceAPI.java
- application/android/app/src/main/java/com/group12/beabee/network/mocking/MockService.java
- application/android/app/src/main/java/com/group12/beabee/views/entities/IOnTagClickedListener.java
- application/android/app/src/main/java/com/group12/beabee/views/entities/TagCardViewAdapter.java
- application/android/app/src/main/java/com/group12/beabee/views/goals/GoalFragment.java
- application/android/app/src/main/java/com/group12/beabee/views/goals/GroupGoalFragment.java
- application/android/app/src/main/java/com/group12/beabee/views/goals/PrototypeGoalFragment.java
- application/android/app/src/main/java/com/group12/beabee/views/goals/SubgoalFragment.java
- application/android/app/src/main/res/layout/dialog_add_tag.xml
- application/android/app/src/main/res/layout/fragment_goal.xml
- application/android/app/src/main/res/layout/fragment_question.xml
- application/android/app/src/main/res/layout/fragment_reflection.xml
- application/android/app/src/main/res/layout/fragment_routine.xml
- application/android/app/src/main/res/layout/fragment_subgoal.xml
- application/android/app/src/main/res/layout/fragment_task.xml
Now we are able to add tags and remove tags from Goals and GroupGoals
Also we can display these tags when we publish our goal in the marketplace
> Add tag and Remove Tag feature

- application/frontend/src/pages/EntityPage.tsx
> Complete Button is added
